---
  - name: Update the repository
    dnf:
      name: "*"
      state: latest
      update_cache: yes
  - name: Install packages from repository
    become: yes
    dnf:
      name: "{{ packagesdep }}"
      state: latest
      update_cache: yes
    vars:
      packagesdep:
      - python3
      - policycoreutils-python-utils
      - git
      - httpd
      - vsftpd
      - firewalld
