---
  - name: Enable firewalld
    service: name=firewalld state=started enabled=yes
  - name: Set dmz as default policy
    command: firewall-cmd --set-default-zone=public
  - name: Allow http/https/ftp
    command: firewall-cmd --zone=public --permanent --add-service=http --add-service=https --add-service=ftp
  - name: Restart firewalld service
    service: name=firewalld state=restarted
  - name: Create upload directory
    file:
      path: /var/ftp/pub/upload
      state: directory
      recurse: yes
      mode: '0757'
  - name: Setup Selinux for anonymous upload     
    shell: | 
      semanage fcontext -a -t public_content_t /var/ftp
      restorecon -Rvv /var/ftp/
      semanage fcontext -a -t public_content_rw_t "/var/ftp/pub(/.*)?"
      restorecon -R -v /var/ftp/pub
      setsebool -P allow_ftpd_anon_write on
    notify:
    - Restart vsftpd
