---
  - name: Replace vsftp config
    template:
      src: config.j2
      dest: "/etc/vsftpd/vsftpd.conf"
  - name: Start vsftpd service
    service: name=vsftpd state=started enabled=yes
  - name: Check service status
    service_facts:
  - debug:
      var: ansible_facts.services["vsftpd.service"].state